package com.example.designsystem.theme

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

/**
 * Product-specific semantic colors layered on Material roles.
 * Prefer [androidx.compose.material3.MaterialTheme.colorScheme] when a Material role already fits.
 *
 * [brand] remains #073028 for large green fills in both themes.
 * Interactive content on dark surfaces should use [selectedContent] / Material primary instead.
 */
@Immutable
data class IhsanSemanticColors(
    val brand: Color,
    val onBrand: Color,
    val brandElevated: Color,
    val surfaceBase: Color,
    val surfaceElevated: Color,
    val surfaceMuted: Color,
    val surfaceMint: Color,
    val surfaceWarm: Color,
    val textPrimary: Color,
    val textSecondary: Color,
    val textDisabled: Color,
    val textSecondaryMuted: Color,
    val borderSubtle: Color,
    val divider: Color,
    val selectedContainer: Color,
    val selectedContent: Color,
    val unselectedContent: Color,
    val navigationSurface: Color,
    val navigationIndicator: Color,
    val navigationOutline: Color,
    val navigationIconHalo: Color,
    val overlayScrim: Color,
    val fieldContainer: Color,
    val fieldBorder: Color,
    val fieldFocusedBorder: Color,
    val success: Color,
    val onSuccess: Color,
    val warning: Color,
    val onWarning: Color,
    val charityOffer: Color,
    val charityOfferContainer: Color,
    val charityRequest: Color,
    val charityRequestContainer: Color,
    val progressActive: Color,
    val progressTrack: Color,
    val accentWarm: Color,
    val quickActionSurface: Color,
    val whatsapp: Color,
    val favorite: Color
)

val LightIhsanSemanticColors = IhsanSemanticColors(
    brand = PrimaryTeal,
    onBrand = OnPrimaryWhite,
    brandElevated = DarkBrandElevated,
    surfaceBase = BackgroundCream,
    surfaceElevated = SurfaceWhite,
    surfaceMuted = Color(0xFFF9F9F9),
    surfaceMint = Color(0xFFF1F8F6),
    surfaceWarm = Color(0xFFF8F4EE),
    textPrimary = OnSurfaceDark,
    textSecondary = Neutral500,
    textDisabled = Neutral400,
    textSecondaryMuted = Neutral500,
    borderSubtle = Neutral200,
    divider = Neutral200,
    selectedContainer = PrimaryTeal,
    selectedContent = OnPrimaryWhite,
    unselectedContent = PrimaryTeal.copy(alpha = 0.55f),
    navigationSurface = SurfaceWhite,
    navigationIndicator = PrimaryTeal,
    navigationOutline = Neutral200,
    navigationIconHalo = OnPrimaryWhite.copy(alpha = 0.16f),
    overlayScrim = Color(0x52000000),
    fieldContainer = SurfaceWhite,
    fieldBorder = Neutral300,
    fieldFocusedBorder = PrimaryTeal,
    success = Color(0xFF2E7D32),
    onSuccess = OnPrimaryWhite,
    warning = Color(0xFFE65100),
    onWarning = OnPrimaryWhite,
    charityOffer = Color(0xFF2E7D32),
    charityOfferContainer = Color(0xFFE8F5E9),
    charityRequest = Color(0xFFE65100),
    charityRequestContainer = Color(0xFFFFF3E0),
    progressActive = PrimaryTeal,
    progressTrack = PrimaryTeal.copy(alpha = 0.12f),
    accentWarm = Color(0xFFC66927),
    quickActionSurface = Color(0xFFF3F6F5),
    whatsapp = Color(0xFF25D366),
    favorite = Color(0xFFE91E63)
)

val DarkIhsanSemanticColors = IhsanSemanticColors(
    brand = PrimaryTeal,
    onBrand = OnPrimaryWhite,
    brandElevated = DarkBrandElevated,
    surfaceBase = DarkBackground,
    surfaceElevated = DarkSurfaceElevated,
    surfaceMuted = DarkSurfaceMuted,
    surfaceMint = DarkInteractivePrimaryContainer.copy(alpha = 0.55f),
    surfaceWarm = DarkSurfaceWarm,
    textPrimary = DarkOnSurface,
    textSecondary = DarkOnSurfaceVariant,
    textDisabled = DarkOnSurfaceVariant.copy(alpha = 0.55f),
    textSecondaryMuted = DarkOnSurfaceVariant,
    borderSubtle = DarkOutlineVariant,
    divider = DarkOutlineVariant,
    selectedContainer = DarkInteractivePrimaryContainer,
    selectedContent = DarkInteractivePrimary,
    unselectedContent = DarkOnSurfaceVariant,
    navigationSurface = DarkSurfaceElevated,
    navigationIndicator = DarkInteractivePrimaryContainer,
    navigationOutline = DarkOutlineVariant,
    navigationIconHalo = DarkInteractivePrimary.copy(alpha = 0.18f),
    overlayScrim = DarkScrim,
    fieldContainer = DarkSurfaceMuted,
    fieldBorder = DarkOutline,
    fieldFocusedBorder = DarkInteractivePrimary,
    success = Color(0xFF81C784),
    onSuccess = OnDarkInteractivePrimary,
    warning = Color(0xFFFFB74D),
    onWarning = OnDarkInteractivePrimary,
    charityOffer = Color(0xFF81C784),
    charityOfferContainer = Color(0xFF1B5E20).copy(alpha = 0.45f),
    charityRequest = Color(0xFFFFB74D),
    charityRequestContainer = Color(0xFFE65100).copy(alpha = 0.35f),
    progressActive = DarkInteractivePrimary,
    progressTrack = DarkInteractivePrimary.copy(alpha = 0.22f),
    accentWarm = Color(0xFFFFB74D),
    quickActionSurface = DarkSurfaceMuted,
    whatsapp = Color(0xFF25D366),
    favorite = Color(0xFFF48FB1)
)

val LocalIhsanColors = staticCompositionLocalOf { LightIhsanSemanticColors }
